# Make sure to check the documentation at http://goreleaser.com
checksum:
  name_template: 'checksums.txt'
krews:
  - name: kubectl-season
    homepage: https://github.com/scraly/krew-index
    index:
      owner: scraly
      name: krew-index