apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: season
spec:
  homepage: https://github.com/scraly/kubectl-season
  shortDescription: Display seasonal emoji randomly before resources name
  version: v0.0.4
  description: |
    This plugin allows you to add randomly a seasonal (halloween, christmas, easter...) emoji just before the resources name. It's a special seasonal mode.
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/scraly/kubectl-season/archive/v0.0.4.tar.gz
    sha256: 7331819379ca14da988d2537904381b6186c989d527719cb1e0fd212293d749e
    bin: kubectl-season-0.0.4/kubectl-season